PR: complete section 1 layout
MitskevichVS/layout pull request #1
Opened 2020-01-10 13:41 UTC by MitskevichVS

2020-01-10 13:53 UTC, DmitryMishin commented on dist/css/style.css
> +#one:checked~.controls label:nth-of-type(1),
использовать айдишки для стилей - плохая идея. Если у тебя будут компоненты, где нужно будет в специфических местах перебивать стили, то придется поиграться или с !important, или с наследованием

2020-01-10 13:54 UTC, DmitryMishin commented on dist/css/style.css
> +    font-size: 2.4em;
про `em` мы уже поговорили :)

2020-01-10 13:57 UTC, DmitryMishin commented on dist/css/style.css
> +    margin: 3.5% 0% 0% 0%;
для чистоты кода обычно не пишут ничего после 0, т.е. margin: 3.5% 0 0 0;
И с вещественными числами поосторожнее, я точно не помню что именно, но есть места, когда браузера по-разному интерпретируют их

2020-01-10 14:02 UTC, dzmitrymishyn requested changes
Про картинки, если нет прозрачных фонов, то лучше их конвертировать в jpg + кидать в оптимизатор, смотря какое качество нужно. PNG весят больше
Еще 1 замечание. Если изменяешь html, делаешь новые секции и так далее, то для ПРа лучше сделать скрины, желательно по несколько штук на каждый html (на несколько разрешений: мобила, планшет, десктоп например)

2020-01-10 14:10 UTC, danymill commented on dist/css/style.css
> +    margin: 3.5% 0% 0% 0%;
Тут дело даже не с вещественными, а больше проблемы с округлениями. Поэтому я тебе бы советовал пересмотреть все места, где и целые нечетные и по возможности использовать четное число. Например, буквально сегодня я исправлял баг, когда флекс не мог выровнять 2 объекта по вертикальной оси корректно. Все было из-за того, что высота одного из них была 17пикс, против 12 пикс другого. Так вот этот нечетный пиксель время от времени располагал элемент то немного выше, то ниже... Нужно просто пытаться предусматривать такие кейсы)) Нельзя буздумно)) 15пикс маржин по бокам - это же даже очень неплохо и не приносит в большинстве проблем))))

2020-01-10 14:11 UTC, danymill commented
> Про картинки, если нет прозрачных фонов, то лучше их конвертировать в jpg + кидать в оптимизатор, смотря какое качество нужно. PNG весят больше
> Еще 1 замечание. Если изменяешь html, делаешь новые секции и так далее, то для ПРа лучше сделать скрины, желательно по несколько штук на каждый html (на несколько разрешений: мобила, планшет, десктоп например)

У нас пока десктоп только, поэтому ОК и 1 скрин.

2020-01-10 14:13 UTC, danymill commented on dist/css/style.css
> +    margin: 3.5% 0% 0% 0%;
Еще ремарка в данном случае: а ведь `%` при вычислении может дать как четное, так и нечетное число в пикселях в итоге и потому в данном конкретном случае неважно))))

2020-01-13 07:31 UTC, merged

2020-01-13 07:41 UTC, danymill commented on dist/css/style.css
> +    width: 100%;
Есть ли необходимость здесь явно задавать ширину?

2020-01-13 07:41 UTC, danymill commented on dist/css/style.css
> +    transition: all 0.6s ease-in;
есть ли обоснованная необходимость тут задавать `all`?

2020-01-13 08:00 UTC, danymill commented on dist/css/style.css
> +.slider__radioinput-fourth:checked~.slide4 {
Переделать под динамический контент

2020-01-13 08:10 UTC, MitskevichVS commented on dist/css/style.css
> +    font-size: 2.4em;
fixed

2020-01-13 13:15 UTC, MitskevichVS commented on dist/css/style.css
> +    width: 100%;
fixed

2020-01-13 13:15 UTC, MitskevichVS commented on dist/css/style.css
> +    transition: all 0.6s ease-in;
fixed

2020-01-13 13:15 UTC, MitskevichVS commented on dist/css/style.css
> +.slider__radioinput-fourth:checked~.slide4 {
fixed

2020-01-13 13:15 UTC, MitskevichVS commented on dist/css/style.css
> +#one:checked~.controls label:nth-of-type(1),
fixed

2020-01-14 10:18 UTC, MitskevichVS commented on dist/css/style.css
> +    margin: 3.5% 0% 0% 0%;
fixed